Upload new homework
hristijanpetkovski/Semos-JavaScript pull request #1
Opened 2020-11-15 17:33 UTC by hristijanpetkovski

2020-11-15 20:03 UTC, dpeshevski requested changes

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/DataTypes.js
> +
линија 19 и 20 треба да бидат преместени тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    var secondDecimal =Number(secondDecimal)
`var`, зарем!? 
дали вредноста на `secondDecimal` се променува? 
веќе имаш `secondDecimal` кој што е **parameter** од data type String кој што репрезентира floating-point number, и доаѓа од самата function.
немаш `;` на крај.

`const convertedSecondDecimal = Number(secondDecimal);`

-- истово за линија 19, 27.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    // Write code that uses console.log to print the sum of 'firstDecimal' and 'secondDecimal' (converted to a Number            type) on a new line.
линија 23 и 24 => тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    // Write code that uses console.log to print the concatenation of 'firstString' and 'secondString' on a new line. The        variable 'firstString' must be printed first.
линија 26 и 27 => тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/HelloWordld.js
> +    // Write a line of code that prints parameterVariable to stdout using console.log:
линија 13 премести ја тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  // Print the area of the circle:
линија 5 премести ја тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  // Print the perimeter of the circle:
линија 6 премести ја тука.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let area = (Math.PI * (r * r));
`let`!? дали ја променува вредноста? не. што се користи во таков случај? `const`

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let perimetar = (2 * Math.PI * r);
`const`

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let perimetar = (2 * Math.PI * r);
зошто `()`?

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let perimetar = (2 * Math.PI * r);
зошто не ја декларираш `Math.PI` како variable name. нешто кога се повторува се декларира како променлива. размисли кое помеѓу `const` и `let` ќе го користиш, односно кое е правилно во случајов..

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let area = (Math.PI * (r * r));
Чисто да знаеш дека `(r * r)`  може да го замениш и со `Math.pow(r, 2)` или `(r ** 2)`.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  const r =readLine();
празно место секогаш и секаде после `=` и `;` на крај од линијата.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/DataTypes.js
> +const secondString = 'is the best place to learn and practice coding!';
линија 13, 14, и 15 не ти се потребни, избириши ги. 
Никаде не ги користиш, знаеш зошто? Доаѓаат од самата фунција како parameters.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/ArithmeticOperators.js
> +const width =Number(4.5);
line 9 и 10 никаде не се користат.

2020-11-15 20:03 UTC, dpeshevski commented on homeworks/HelloWordld.js
> +const parameterVariable = 'Welcome to 10 Days of JavaScript!'
line 8 никаде не се користи.

2020-11-15 20:46 UTC, hristijanpetkovski commented on homeworks/ArithmeticOperators.js
> +const width =Number(4.5);
Kako mislite nikade ne se koristat?

2020-11-15 21:36 UTC, dpeshevski commented on homeworks/ArithmeticOperators.js
> +const width =Number(4.5);
Овие се само декларирани како променливи, и никаде во решението не се користат. 
`length` и `width` доаѓаат како **parameters** од самата функција. 
Функцијата си испраќа вредности за нив при секое повикување.

2020-11-16 13:50 UTC, hristijanpetkovski commented on homeworks/ArithmeticOperators.js
> +const width =Number(4.5);
Aha te razbrav i bez tie mi raboti :D

2020-11-16 13:51 UTC, hristijanpetkovski commented on homeworks/DataTypes.js
> +const secondString = 'is the best place to learn and practice coding!';
Ovde go imam istiot slucaj kako i gore taka ? Neznaev deka doagjaat od samata funkcija.

2020-11-16 13:59 UTC, hristijanpetkovski commented on homeworks/DataTypes.js
> +    var secondDecimal =Number(secondDecimal)
so const convertedSecondDecimal = Number(secondDecimal); 
rezultatot koj mi iskaca kakoj moj output e 44.32 , a potrebno e 8.32

2020-11-16 14:16 UTC, hristijanpetkovski commented on homeworks/LetandConst.js
> +  let perimetar = (2 * Math.PI * r);
Kje treba so const ili gresam?
i na koj nacin mozam da ja deklariram kako variable name?

2020-11-16 14:38 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  let perimetar = (2 * Math.PI * r);
Постојат два начина во случајов од кој еден е точен. Обиди се да дознаеш кој и зошто.

`const PI = Math.PI;`


`let PI = Math.PI;`

2020-11-16 14:38 UTC, dpeshevski commented on homeworks/DataTypes.js
> +const secondString = 'is the best place to learn and practice coding!';
Да. Исто е.

2020-11-16 14:47 UTC, dpeshevski requested changes

2020-11-16 14:47 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    var secondDecimal =Number(secondDecimal)
Ги извриша линија 13,14 и 15, така?
Ова `convertedSecondDecimal` го замени на линија 23, така?
Го смени variable name во console.log?

2020-11-16 17:24 UTC, dpeshevski requested changes

2020-11-16 17:24 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
`PI` во try делот ја менува вредноста, значи не е constant :)

2020-11-16 17:27 UTC, hristijanpetkovski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
epa od dvete ednoto e sepak bev blisku :D

2020-11-16 17:33 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
Ако не е црно, бело е - нема друго. :) Те молам пробај со другото и види како ќе се однесува. Може да ти дава тоа што го печати во `catch` делот дека е сменета вредноста, ама пробај ипак.

2020-11-16 17:35 UTC, hristijanpetkovski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
So const kako sto go imam napraveno raboteshe no kje go promenam zatoa bev siguren deka e toa..

2020-11-16 17:39 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
Види со `let` што ќе ти враќа, ако ти работи со `const` на крај а со `let` ти враќа грешка тогаш остави го со `const` само те молам пиши ми за да го затвориме PR.

2020-11-16 17:44 UTC, hristijanpetkovski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
So const mi raboti so let ne raboti

2020-11-16 17:52 UTC, dpeshevski requested changes

2020-11-16 17:52 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    const convertedSecondString = (secondString);
ups... зошто тука постои ова `convertedSecondString` во што го конвертираш? 
String е посекако, правиш конкатенација на две вредности кои се Strings, во претходните случаеви `secondInteger` и `secondDecimal` беа стрингови кои за да пресметаш сума требаше да бидат од тип број, инаку што ќе се случи доколку испечатиш `console.log(5+'55')`?

2020-11-16 17:52 UTC, dpeshevski commented on homeworks/DataTypes.js
> +    console.log(firstString + convertedSecondString);
Вака треба да биде. 
`console.log(firstString + secondString);`

2020-11-16 17:55 UTC, dpeshevski commented on homeworks/LetandConst.js
> +  const PI = Math.PI;
Ок, тогаш нека остане со `const`. Прочитај за `let` и `const`, кои се разликите и слично.

2020-11-24 09:06 UTC, merged